### ISSUE TITLE
Change in requirements

### ISSUE THREAD

**Issue by samvbeckmann** [samvbeckmann/christmas-lights#13]
It turns out that the LED strip (at least one of the length we want) can be powered directly through the tiva board, no external power required. Do we want to submit a requirements update that reflects this?

**Comment by josephedmunds** [comment]
If we plan on powering it in that way, we should

**Comment by samvbeckmann** [comment]
We could _theoretically_ get away with the current requirements, and a standard USB power socket. However, we might want to generify the requirements a bit, and simply say that the whole system will be powered via a USB connection.

**Comment by josephedmunds** [comment]
The change would be from "US electrical outlet" to "USB connection", then?

**Comment by samvbeckmann** [comment]
I sent the request to Hook, waiting for him to reply.

**Comment by samvbeckmann** [comment]
Approved by Hook.
